# Generated by Django 2.2.5 on 2019-09-24 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes_app', '0002_auto_20190924_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='favorites',
            field=models.ManyToManyField(related_name='favorites', to='quotes_app.User'),
        ),
    ]
